CREATE TABLE `videos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `lens` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '镜头',
  `size` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件大小',
  `resolution` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分辨率',
  `aspect_ratio` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '宽高比',
  `colour` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '颜色',
  `user_id` int NOT NULL COMMENT '创建者',
  `thumb` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '缩略图',
  `url` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '视频地址',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `desc` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '视频描述',
  `released` int NOT NULL COMMENT '发布状态',
  `keywords` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标签',
  `views` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' COMMENT '视频views',
  `downnums` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' COMMENT '视频下载数量',
  `source` int NOT NULL COMMENT '来源 0-默认 1-好机绘',
  `workflow_id` int NOT NULL COMMENT '工作流ID',
  `workflow_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '工作流名称',
  `type` int NOT NULL COMMENT '来源 1-用户 2-AIGC',
  PRIMARY KEY (`id`),
  KEY `idx_source` (`source`),
  KEY `idx_workflow_id` (`workflow_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_desc` (`desc`),
  KEY `idx_keywords` (`keywords`),
  KEY `idx_type` (`type`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;